POST http://18.188.110.208/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "admin54321"
}

# 2|n3aM9SnYoybyuA2XokyKpF1cKWz1CQG6SET7lO85aa8b65ad
### perfil
GET http://127.0.0.1:8000/api/perfil
Accept: application/json
Authorization: Bearer 22|PnXq95mXmHXbivvt2MYR2lQXjM1hl0xRi4I9PeaY5898c453

### Registro Usuario
POST http://18.188.110.208/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@mail.com",
    "password": "admin54321",
    "c_password": "admin54321"
}


### get perfil
GET http://127.0.0.1:8000/api/v1/auth/profile
Accept: application/json
Authorization: Bearer 6|wuyCa9vPpAR8ud3hYHzp84kqNXDKbCO9D0FatUAbb23b889a

### logout

POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 6|wuyCa9vPpAR8ud3hYHzp84kqNXDKbCO9D0FatUAbb23b889a
